// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settleora.Api.Persistence;

#nullable disable

namespace Settleora.Api.Persistence.Migrations
{
    [DbContext(typeof(SettleoraDbContext))]
    [Migration("20260501143101_AddAuthCredentialsSessionsAuditSchemaFoundation")]
    partial class AddAuthCredentialsSessionsAuditSchemaFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_accounts_user_profile_id");

                    b.ToTable("auth_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_accounts_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_auth_account_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("RequestId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("request_id");

                    b.Property<string>("SafeMetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("safe_metadata_json");

                    b.Property<Guid?>("SubjectAuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_auth_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorAuthAccountId")
                        .HasDatabaseName("ix_auth_audit_events_actor_auth_account_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_auth_audit_events_occurred_at_utc");

                    b.HasIndex("SubjectAuthAccountId")
                        .HasDatabaseName("ix_auth_audit_events_subject_auth_account_id");

                    b.ToTable("auth_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_audit_events_action_not_blank", "length(btrim(action)) > 0");

                            t.HasCheckConstraint("ck_auth_audit_events_correlation_id_not_blank", "correlation_id IS NULL OR length(btrim(correlation_id)) > 0");

                            t.HasCheckConstraint("ck_auth_audit_events_outcome", "outcome IN ('success', 'failure', 'denied', 'revoked', 'expired', 'blocked_by_policy')");

                            t.HasCheckConstraint("ck_auth_audit_events_request_id_not_blank", "request_id IS NULL OR length(btrim(request_id)) > 0");

                            t.HasCheckConstraint("ck_auth_audit_events_safe_metadata_json_not_blank", "safe_metadata_json IS NULL OR length(btrim(safe_metadata_json)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("provider_subject");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId")
                        .HasDatabaseName("ix_auth_identities_auth_account_id");

                    b.HasIndex("ProviderType", "ProviderName", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_provider_lookup");

                    b.ToTable("auth_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_identities_provider_name_not_blank", "length(btrim(provider_name)) > 0");

                            t.HasCheckConstraint("ck_auth_identities_provider_subject_not_blank", "length(btrim(provider_subject)) > 0");

                            t.HasCheckConstraint("ck_auth_identities_provider_type", "provider_type IN ('local', 'oidc')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("NetworkAddressHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("network_address_hash");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgentSummary")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_agent_summary");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId")
                        .HasDatabaseName("ix_auth_sessions_auth_account_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_auth_sessions_expires_at_utc");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_refresh_token_hash")
                        .HasFilter("refresh_token_hash IS NOT NULL");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_session_token_hash");

                    b.ToTable("auth_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_sessions_device_label_not_blank", "device_label IS NULL OR length(btrim(device_label)) > 0");

                            t.HasCheckConstraint("ck_auth_sessions_network_address_hash_not_blank", "network_address_hash IS NULL OR length(btrim(network_address_hash)) > 0");

                            t.HasCheckConstraint("ck_auth_sessions_refresh_token_hash_not_blank", "refresh_token_hash IS NULL OR length(btrim(refresh_token_hash)) > 0");

                            t.HasCheckConstraint("ck_auth_sessions_revocation_reason_not_blank", "revocation_reason IS NULL OR length(btrim(revocation_reason)) > 0");

                            t.HasCheckConstraint("ck_auth_sessions_session_token_hash_not_blank", "length(btrim(session_token_hash)) > 0");

                            t.HasCheckConstraint("ck_auth_sessions_status", "status IN ('active', 'revoked', 'expired')");

                            t.HasCheckConstraint("ck_auth_sessions_user_agent_summary_not_blank", "user_agent_summary IS NULL OR length(btrim(user_agent_summary)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.LocalPasswordCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordHashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password_hash_algorithm");

                    b.Property<string>("PasswordHashAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("password_hash_algorithm_version");

                    b.Property<string>("PasswordHashParameters")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash_parameters");

                    b.Property<bool>("RequiresRehash")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_rehash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_local_password_credentials_auth_account_id");

                    b.ToTable("local_password_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_local_password_credentials_hash_algorithm_not_blank", "length(btrim(password_hash_algorithm)) > 0");

                            t.HasCheckConstraint("ck_local_password_credentials_hash_algorithm_version_not_blank", "length(btrim(password_hash_algorithm_version)) > 0");

                            t.HasCheckConstraint("ck_local_password_credentials_hash_not_blank", "length(btrim(password_hash)) > 0");

                            t.HasCheckConstraint("ck_local_password_credentials_hash_parameters_not_blank", "length(btrim(password_hash_parameters)) > 0");

                            t.HasCheckConstraint("ck_local_password_credentials_status", "status IN ('active', 'disabled', 'revoked')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.SystemRoleAssignment", b =>
                {
                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("AssignedByAuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_auth_account_id");

                    b.HasKey("AuthAccountId", "Role");

                    b.HasIndex("AssignedByAuthAccountId")
                        .HasDatabaseName("ix_system_role_assignments_assigned_by_auth_account_id");

                    b.ToTable("system_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_role_assignments_role", "role IN ('owner', 'admin', 'user')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("GroupId", "UserProfileId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_group_memberships_user_profile_id");

                    b.ToTable("group_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_memberships_role", "role IN ('owner', 'member')");

                            t.HasCheckConstraint("ck_group_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_profile_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserProfileId")
                        .HasDatabaseName("ix_user_groups_created_by_user_profile_id");

                    b.ToTable("user_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_groups_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_default_currency_uppercase_iso", "default_currency IS NULL OR default_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_user_profiles_display_name_not_blank", "length(btrim(display_name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Settleora.Api.Domain.Auth.AuthAccount", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_accounts_user_profiles_user_profile_id");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAuditEvent", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "ActorAuthAccount")
                        .WithMany("ActorAuditEvents")
                        .HasForeignKey("ActorAuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auth_audit_events_actor_auth_account");

                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "SubjectAuthAccount")
                        .WithMany("SubjectAuditEvents")
                        .HasForeignKey("SubjectAuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auth_audit_events_subject_auth_account");

                    b.Navigation("ActorAuthAccount");

                    b.Navigation("SubjectAuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthIdentity", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("Identities")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_auth_accounts_auth_account_id");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthSession", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("Sessions")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_auth_accounts_auth_account_id");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.LocalPasswordCredential", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("LocalPasswordCredentials")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_local_password_credentials_auth_accounts_auth_account_id");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.SystemRoleAssignment", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AssignedByAuthAccount")
                        .WithMany("AssignedRoleAssignments")
                        .HasForeignKey("AssignedByAuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_role_assignments_assigned_by_auth_account");

                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_assignments_auth_account");

                    b.Navigation("AssignedByAuthAccount");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "CreatedByUserProfile")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.Navigation("ActorAuditEvents");

                    b.Navigation("AssignedRoleAssignments");

                    b.Navigation("Identities");

                    b.Navigation("LocalPasswordCredentials");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Sessions");

                    b.Navigation("SubjectAuditEvents");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
