// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settleora.Api.Persistence;

#nullable disable

namespace Settleora.Api.Persistence.Migrations
{
    [DbContext(typeof(SettleoraDbContext))]
    [Migration("20260501093928_AddUsersGroupsSchemaFoundation")]
    partial class AddUsersGroupsSchemaFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("GroupId", "UserProfileId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_group_memberships_user_profile_id");

                    b.ToTable("group_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_memberships_role", "role IN ('owner', 'member')");

                            t.HasCheckConstraint("ck_group_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_profile_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserProfileId")
                        .HasDatabaseName("ix_user_groups_created_by_user_profile_id");

                    b.ToTable("user_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_groups_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_default_currency_uppercase_iso", "default_currency IS NULL OR default_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_user_profiles_display_name_not_blank", "length(btrim(display_name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "CreatedByUserProfile")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
