// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settleora.Api.Persistence;

#nullable disable

namespace Settleora.Api.Persistence.Migrations
{
    [DbContext(typeof(SettleoraDbContext))]
    [Migration("20260501131636_AddAuthIdentitySchemaFoundation")]
    partial class AddAuthIdentitySchemaFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_accounts_user_profile_id");

                    b.ToTable("auth_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_accounts_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("provider_subject");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId")
                        .HasDatabaseName("ix_auth_identities_auth_account_id");

                    b.HasIndex("ProviderType", "ProviderName", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_provider_lookup");

                    b.ToTable("auth_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_identities_provider_name_not_blank", "length(btrim(provider_name)) > 0");

                            t.HasCheckConstraint("ck_auth_identities_provider_subject_not_blank", "length(btrim(provider_subject)) > 0");

                            t.HasCheckConstraint("ck_auth_identities_provider_type", "provider_type IN ('local', 'oidc')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.SystemRoleAssignment", b =>
                {
                    b.Property<Guid>("AuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_account_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("AssignedByAuthAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_auth_account_id");

                    b.HasKey("AuthAccountId", "Role");

                    b.HasIndex("AssignedByAuthAccountId")
                        .HasDatabaseName("ix_system_role_assignments_assigned_by_auth_account_id");

                    b.ToTable("system_role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_role_assignments_role", "role IN ('owner', 'admin', 'user')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("GroupId", "UserProfileId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_group_memberships_user_profile_id");

                    b.ToTable("group_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_memberships_role", "role IN ('owner', 'member')");

                            t.HasCheckConstraint("ck_group_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_profile_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserProfileId")
                        .HasDatabaseName("ix_user_groups_created_by_user_profile_id");

                    b.ToTable("user_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_groups_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_default_currency_uppercase_iso", "default_currency IS NULL OR default_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_user_profiles_display_name_not_blank", "length(btrim(display_name)) > 0");
                        });
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Settleora.Api.Domain.Auth.AuthAccount", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_accounts_user_profiles_user_profile_id");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthIdentity", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("Identities")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_auth_accounts_auth_account_id");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.SystemRoleAssignment", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AssignedByAuthAccount")
                        .WithMany("AssignedRoleAssignments")
                        .HasForeignKey("AssignedByAuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_role_assignments_assigned_by_auth_account");

                    b.HasOne("Settleora.Api.Domain.Auth.AuthAccount", "AuthAccount")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_assignments_auth_account");

                    b.Navigation("AssignedByAuthAccount");

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.GroupMembership", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.HasOne("Settleora.Api.Domain.Users.UserProfile", "CreatedByUserProfile")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Auth.AuthAccount", b =>
                {
                    b.Navigation("AssignedRoleAssignments");

                    b.Navigation("Identities");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Settleora.Api.Domain.Users.UserProfile", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
