categories:
  - financial
icon_url: https://raw.githubusercontent.com/tommytang213/Settleora/71786f94e39f27b89f4b07efb00532d7fc356079/apps/mobile/web/icons/Icon-512.png
screenshots: []
tags:
  - finance
  - productivity
  - self-hosted
