import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "yaml";

const specPath = "packages/contracts/openapi/settleora.v1.yaml";
const webOutputPath = "packages/client-web/src/generated";
const dartOutputPath = "packages/client-dart/generated";

const generatedHeader = [
  "<auto-generated>",
  `Generated by tools/generate-clients.mjs from ${specPath}.`,
  "Do not edit this file by hand.",
  "</auto-generated>"
];

const httpMethods = ["get", "post", "put", "patch", "delete"];

const spec = parse(await readFile(specPath, "utf8"));
const operations = collectOperations(spec);
const schemas = {
  ...(spec.components?.schemas ?? {}),
  ...collectInlineSuccessSchemas(operations)
};

await cleanGeneratedDirectory(webOutputPath);
await cleanGeneratedDirectory(dartOutputPath);

await writeFile(join(webOutputPath, "models.ts"), generateTypeScriptModels(schemas), "utf8");
await writeFile(join(webOutputPath, "client.ts"), generateTypeScriptClient(operations), "utf8");
await writeFile(join(webOutputPath, "index.ts"), generateTypeScriptIndex(), "utf8");

await writeFile(join(dartOutputPath, "models.dart"), generateDartModels(schemas), "utf8");
await writeFile(join(dartOutputPath, "client.dart"), generateDartClient(operations), "utf8");
await writeFile(join(dartOutputPath, "settleora_api.dart"), generateDartIndex(), "utf8");

console.log(`Generated web client in ${webOutputPath}`);
console.log(`Generated Dart client in ${dartOutputPath}`);

function collectOperations(openApiSpec) {
  const collected = [];
  const paths = openApiSpec.paths ?? {};

  for (const path of Object.keys(paths).sort()) {
    const pathItem = paths[path] ?? {};

    for (const method of httpMethods) {
      const operation = pathItem[method];
      if (!operation?.operationId) {
        continue;
      }

      const pathParameters = [
        ...(pathItem.parameters ?? []),
        ...(operation.parameters ?? [])
      ].filter((parameter) => parameter.in === "path");

      const requestSchema = operation.requestBody?.content?.["application/json"]?.schema;
      const successResponse = getSuccessResponse(operation.responses ?? {});
      const successSchema = successResponse?.content?.["application/json"]?.schema;
      const successTypeName = successSchema ? schemaTypeNameForOperation(operation.operationId, successSchema) : "void";
      const requiresAuth = operationRequiresAuth(operation);

      collected.push({
        method: method.toUpperCase(),
        path,
        operationId: operation.operationId,
        pathParameters,
        requestSchema,
        successSchema,
        successTypeName,
        requiresAuth
      });
    }
  }

  return collected;
}

function collectInlineSuccessSchemas(collectedOperations) {
  const inlineSchemas = {};

  for (const operation of collectedOperations) {
    if (!operation.successSchema || operation.successSchema.$ref) {
      continue;
    }

    inlineSchemas[operation.successTypeName] = operation.successSchema;
  }

  return inlineSchemas;
}

function getSuccessResponse(responses) {
  for (const statusCode of Object.keys(responses).sort()) {
    if (/^2\d\d$/.test(statusCode)) {
      return responses[statusCode];
    }
  }

  return null;
}

function operationRequiresAuth(operation) {
  if (!Array.isArray(operation.security)) {
    return false;
  }

  return operation.security.some((entry) => Object.keys(entry ?? {}).length > 0);
}

function schemaTypeNameForOperation(operationId, schema) {
  if (schema.$ref) {
    return refName(schema.$ref);
  }

  return `${toPascalCase(operationId)}Response`;
}

async function cleanGeneratedDirectory(directory) {
  await mkdir(directory, { recursive: true });

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name === ".gitkeep") {
      continue;
    }

    await rm(join(directory, entry.name), { force: true, recursive: true });
  }
}

function generateTypeScriptModels(modelSchemas) {
  const lines = [
    ...typescriptHeader(),
    ""
  ];

  for (const [name, schema] of Object.entries(modelSchemas)) {
    lines.push(...typescriptDescription(schema.description));

    if (schema.type === "object" || schema.properties) {
      lines.push(`export interface ${name} {`);
      const required = new Set(schema.required ?? []);

      for (const [propertyName, propertySchema] of Object.entries(schema.properties ?? {})) {
        lines.push(...typescriptDescription(propertySchema.description, "  "));
        const optional = required.has(propertyName) ? "" : "?";
        lines.push(`  ${typescriptPropertyName(propertyName)}${optional}: ${typescriptType(propertySchema)};`);
      }

      lines.push("}");
      lines.push("");
      continue;
    }

    lines.push(`export type ${name} = ${typescriptType(schema)};`);
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateTypeScriptClient(collectedOperations) {
  const importedTypes = new Set(["ProblemDetails"]);

  for (const operation of collectedOperations) {
    collectTypeImports(operation.requestSchema, importedTypes);
    if (operation.successSchema) {
      importedTypes.add(operation.successTypeName);
    }
  }

  const lines = [
    ...typescriptHeader(),
    "",
    `import type { ${[...importedTypes].sort().join(", ")} } from "./models";`,
    "",
    "export type SettleoraFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;",
    "",
    "export interface SettleoraClientOptions {",
    "  baseUrl?: string;",
    "  fetch?: SettleoraFetch;",
    "  defaultHeaders?: HeadersInit;",
    "}",
    "",
    "export interface SettleoraRequestOptions {",
    "  headers?: HeadersInit;",
    "  signal?: AbortSignal;",
    "}",
    "",
    "export interface SettleoraAuthenticatedRequestOptions extends SettleoraRequestOptions {",
    "  accessToken: string;",
    "}",
    "",
    "export class SettleoraApiError extends Error {",
    "  constructor(",
    "    readonly status: number,",
    "    readonly statusText: string,",
    "    readonly body: ProblemDetails | unknown",
    "  ) {",
    "    super(`Settleora API request failed with ${status} ${statusText}`);",
    "    this.name = \"SettleoraApiError\";",
    "  }",
    "}",
    "",
    "export class SettleoraApiClient {",
    "  private readonly baseUrl: string;",
    "  private readonly fetchImpl: SettleoraFetch;",
    "  private readonly defaultHeaders: HeadersInit;",
    "",
    "  constructor(options: SettleoraClientOptions = {}) {",
    "    this.baseUrl = options.baseUrl ?? \"/\";",
    "    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);",
    "    this.defaultHeaders = options.defaultHeaders ?? {};",
    "  }",
    ""
  ];

  for (const operation of collectedOperations) {
    lines.push(...generateTypeScriptOperation(operation));
    lines.push("");
  }

  lines.push(
    "  private async request<T>(",
    "    method: string,",
    "    path: string,",
    "    body: unknown,",
    "    options: SettleoraRequestOptions,",
    "    accessToken?: string",
    "  ): Promise<T> {",
    "    const headers = new Headers(this.defaultHeaders);",
    "    for (const [key, value] of new Headers(options.headers ?? {})) {",
    "      headers.set(key, value);",
    "    }",
    "",
    "    if (accessToken) {",
    "      headers.set(\"authorization\", `Bearer ${accessToken}`);",
    "    }",
    "",
    "    const init: RequestInit = {",
    "      method,",
    "      headers,",
    "      signal: options.signal",
    "    };",
    "",
    "    if (body !== undefined) {",
    "      headers.set(\"content-type\", \"application/json\");",
    "      init.body = JSON.stringify(body);",
    "    }",
    "",
    "    const response = await this.fetchImpl(this.resolveUrl(path), init);",
    "",
    "    if (response.status === 204) {",
    "      return undefined as T;",
    "    }",
    "",
    "    const text = await response.text();",
    "    const payload = text.length > 0 ? parseJson(text) : undefined;",
    "",
    "    if (!response.ok) {",
    "      throw new SettleoraApiError(response.status, response.statusText, payload);",
    "    }",
    "",
    "    return payload as T;",
    "  }",
    "",
    "  private resolveUrl(path: string): string {",
    "    const normalizedBaseUrl = this.baseUrl.endsWith(\"/\") ? this.baseUrl : `${this.baseUrl}/`;",
    "    const normalizedPath = path.startsWith(\"/\") ? path.slice(1) : path;",
    "    return new URL(normalizedPath, normalizedBaseUrl).toString();",
    "  }",
    "}",
    "",
    "function parseJson(text: string): unknown {",
    "  try {",
    "    return JSON.parse(text);",
    "  } catch {",
    "    return text;",
    "  }",
    "}"
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateTypeScriptOperation(operation) {
  const requestType = operation.requestSchema ? typescriptType(operation.requestSchema) : null;
  const returnType = operation.successSchema ? operation.successTypeName : "void";
  const parameters = [
    ...operation.pathParameters.map((parameter) => `${parameter.name}: ${typescriptType(parameter.schema)}`),
    ...(requestType ? [`body: ${requestType}`] : []),
    operation.requiresAuth
      ? "options: SettleoraAuthenticatedRequestOptions"
      : "options: SettleoraRequestOptions = {}"
  ];
  const pathExpression = typeScriptPathExpression(operation.path, operation.pathParameters);
  const bodyExpression = requestType ? "body" : "undefined";
  const accessTokenExpression = operation.requiresAuth ? "options.accessToken" : "undefined";

  return [
    `  async ${operation.operationId}(${parameters.join(", ")}): Promise<${returnType}> {`,
    `    return this.request<${returnType}>(\"${operation.method}\", ${pathExpression}, ${bodyExpression}, options, ${accessTokenExpression});`,
    "  }"
  ];
}

function generateTypeScriptIndex() {
  return `${[
    ...typescriptHeader(),
    "",
    "export * from \"./client\";",
    "export * from \"./models\";"
  ].join("\n").trimEnd()}\n`;
}

function typescriptHeader() {
  return generatedHeader.map((line) => `// ${line}`);
}

function typescriptDescription(description, indent = "") {
  if (!description) {
    return [];
  }

  return [
    `${indent}/**`,
    `${indent} * ${sanitizeComment(description)}`,
    `${indent} */`
  ];
}

function typescriptType(schema) {
  if (!schema) {
    return "unknown";
  }

  if (schema.$ref) {
    return refName(schema.$ref);
  }

  if (schema.oneOf) {
    return schema.oneOf.map(typescriptType).join(" | ");
  }

  if (Array.isArray(schema.type)) {
    return schema.type.map((type) => typescriptType({ ...schema, type })).join(" | ");
  }

  if (schema.type === "null") {
    return "null";
  }

  if (schema.enum) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (schema.type === "string") {
    return "string";
  }

  if (schema.type === "integer" || schema.type === "number") {
    return "number";
  }

  if (schema.type === "boolean") {
    return "boolean";
  }

  if (schema.type === "array") {
    const itemType = typescriptType(schema.items);
    const wrappedItemType = itemType.includes(" | ") ? `(${itemType})` : itemType;
    return `${wrappedItemType}[]`;
  }

  if (schema.type === "object" || schema.properties) {
    if (!schema.properties) {
      return "Record<string, unknown>";
    }

    const required = new Set(schema.required ?? []);
    const properties = Object.entries(schema.properties).map(([propertyName, propertySchema]) => {
      const optional = required.has(propertyName) ? "" : "?";
      return `${typescriptPropertyName(propertyName)}${optional}: ${typescriptType(propertySchema)}`;
    });

    return `{ ${properties.join("; ")} }`;
  }

  return "unknown";
}

function collectTypeImports(schema, imports) {
  if (!schema) {
    return;
  }

  if (schema.$ref) {
    imports.add(refName(schema.$ref));
    return;
  }

  for (const child of schema.oneOf ?? []) {
    collectTypeImports(child, imports);
  }

  if (schema.items) {
    collectTypeImports(schema.items, imports);
  }

  for (const propertySchema of Object.values(schema.properties ?? {})) {
    collectTypeImports(propertySchema, imports);
  }
}

function typeScriptPathExpression(path, pathParameters) {
  if (pathParameters.length === 0) {
    return JSON.stringify(path);
  }

  let expression = path;
  for (const parameter of pathParameters) {
    expression = expression.replace(`{${parameter.name}}`, `\${encodeURIComponent(String(${parameter.name}))}`);
  }

  return `\`${expression}\``;
}

function typescriptPropertyName(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function generateDartModels(modelSchemas) {
  const lines = [
    ...dartHeader(),
    "",
    "typedef JsonObject = Map<String, dynamic>;",
    ""
  ];

  for (const [name, schema] of Object.entries(modelSchemas)) {
    lines.push(...dartDescription(schema.description));

    if (schema.type === "object" || schema.properties) {
      lines.push(...generateDartClass(name, schema));
      lines.push("");
      continue;
    }

    lines.push(`typedef ${name} = ${dartType(schema, { nullable: false })};`);

    if (schema.enum) {
      lines.push(`class ${name}Values {`);
      lines.push(`  const ${name}Values._();`);
      for (const value of schema.enum) {
        lines.push(`  static const ${name} ${toCamelCase(String(value))} = ${JSON.stringify(value)};`);
      }
      lines.push(`  static const Set<${name}> values = {${schema.enum.map((value) => toCamelCase(String(value))).join(", ")}};`);
      lines.push("}");
    }

    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateDartClass(name, schema) {
  const required = new Set(schema.required ?? []);
  const properties = Object.entries(schema.properties ?? {}).map(([propertyName, propertySchema]) => ({
    jsonName: propertyName,
    fieldName: toCamelCase(propertyName),
    schema: propertySchema,
    required: required.has(propertyName),
    type: dartType(propertySchema, { nullable: !required.has(propertyName) }),
    nullable: false
  }));

  for (const property of properties) {
    property.nullable = property.type.endsWith("?");
  }

  const lines = [`class ${name} {`];
  lines.push(`  const ${name}({`);
  for (const property of properties) {
    const requiredPrefix = property.required ? "required " : "";
    lines.push(`    ${requiredPrefix}this.${property.fieldName},`);
  }
  lines.push("  });");
  lines.push("");

  for (const property of properties) {
    lines.push(...dartDescription(property.schema.description, "  "));
    lines.push(`  final ${property.type} ${property.fieldName};`);
  }

  lines.push("");
  lines.push(`  factory ${name}.fromJson(JsonObject json) {`);
  lines.push(`    return ${name}(`);
  for (const property of properties) {
    lines.push(`      ${property.fieldName}: ${dartFromJsonExpression(property.schema, `json[${JSON.stringify(property.jsonName)}]`, !property.required)},`);
  }
  lines.push("    );");
  lines.push("  }");
  lines.push("");
  lines.push("  JsonObject toJson() {");
  for (const property of properties.filter((candidate) => candidate.nullable)) {
    lines.push(`    final ${property.fieldName}JsonValue = ${property.fieldName};`);
  }

  if (properties.some((property) => property.nullable)) {
    lines.push("");
  }

  lines.push("    return {");

  for (const property of properties) {
    const propertyExpression = property.nullable ? `${property.fieldName}JsonValue` : property.fieldName;
    const valueExpression = dartToJsonExpression(property.schema, propertyExpression);
    if (property.required) {
      lines.push(`      ${JSON.stringify(property.jsonName)}: ${valueExpression},`);
    } else {
      lines.push(`      if (${propertyExpression} != null) ${JSON.stringify(property.jsonName)}: ${valueExpression},`);
    }
  }

  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  return lines;
}

function generateDartClient(collectedOperations) {
  const lines = [
    ...dartHeader(),
    "",
    "import 'dart:convert';",
    "import 'dart:io';",
    "",
    "import 'models.dart';",
    "",
    "class SettleoraApiException implements Exception {",
    "  const SettleoraApiException(this.statusCode, this.reasonPhrase, this.body);",
    "",
    "  final int statusCode;",
    "  final String reasonPhrase;",
    "  final Object? body;",
    "",
    "  @override",
    "  String toString() => 'SettleoraApiException: $statusCode $reasonPhrase';",
    "}",
    "",
    "class SettleoraApiClient {",
    "  SettleoraApiClient({",
    "    required this.baseUri,",
    "    HttpClient? httpClient,",
    "    Map<String, String>? defaultHeaders,",
    "  })  : _httpClient = httpClient ?? HttpClient(),",
    "        defaultHeaders = Map.unmodifiable(defaultHeaders ?? const {});",
    "",
    "  final Uri baseUri;",
    "  final Map<String, String> defaultHeaders;",
    "  final HttpClient _httpClient;",
    ""
  ];

  for (const operation of collectedOperations) {
    lines.push(...generateDartOperation(operation));
    lines.push("");
  }

  lines.push(
    "  Future<Object?> _send(",
    "    String method,",
    "    String path, {",
    "    Object? body,",
    "    String? accessToken,",
    "    Map<String, String>? headers,",
    "  }) async {",
    "    final request = await _httpClient.openUrl(method, baseUri.resolve(path.startsWith('/') ? path.substring(1) : path));",
    "",
    "    for (final entry in defaultHeaders.entries) {",
    "      request.headers.set(entry.key, entry.value);",
    "    }",
    "",
    "    for (final entry in (headers ?? const <String, String>{}).entries) {",
    "      request.headers.set(entry.key, entry.value);",
    "    }",
    "",
    "    if (accessToken != null && accessToken.isNotEmpty) {",
    "      request.headers.set(HttpHeaders.authorizationHeader, 'Bearer $accessToken');",
    "    }",
    "",
    "    if (body != null) {",
    "      request.headers.contentType = ContentType.json;",
    "      request.write(jsonEncode(body));",
    "    }",
    "",
    "    final response = await request.close();",
    "    final text = await utf8.decodeStream(response);",
    "    final payload = text.isEmpty ? null : jsonDecode(text);",
    "",
    "    if (response.statusCode < 200 || response.statusCode >= 300) {",
    "      throw SettleoraApiException(response.statusCode, response.reasonPhrase, payload);",
    "    }",
    "",
    "    return payload;",
    "  }",
    "}"
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

function generateDartOperation(operation) {
  const responseType = operation.successSchema ? operation.successTypeName : "void";
  const positionalParameters = [
    ...operation.pathParameters.map((parameter) => `${dartType(parameter.schema, { nullable: false })} ${toCamelCase(parameter.name)}`),
    ...(operation.requestSchema ? [`${dartType(operation.requestSchema, { nullable: false })} body`] : [])
  ];
  const namedParameters = [
    ...(operation.requiresAuth ? ["required String accessToken"] : []),
    "Map<String, String>? headers"
  ];
  const parameterText = [
    ...positionalParameters,
    `{${namedParameters.join(", ")}}`
  ].join(", ");
  const pathExpression = dartPathExpression(operation.path, operation.pathParameters);
  const bodyExpression = operation.requestSchema ? "body.toJson()" : "null";
  const accessTokenArgument = operation.requiresAuth ? "accessToken: accessToken," : "";
  const sendStart = operation.successSchema ? "    final payload = await _send(" : "    await _send(";
  const lines = [
    `  Future<${responseType}> ${operation.operationId}(${parameterText}) async {`,
    sendStart,
    `      ${JSON.stringify(operation.method)},`,
    `      ${pathExpression},`,
    `      body: ${bodyExpression},`
  ];

  if (accessTokenArgument) {
    lines.push(`      ${accessTokenArgument}`);
  }

  lines.push(
    "      headers: headers,",
    "    );"
  );

  if (!operation.successSchema) {
    lines.push("  }");
    return lines;
  }

  if (schemaIsObject(schemas[responseType])) {
    lines.push(`    return ${responseType}.fromJson(JsonObject.from(payload as Map));`);
  } else {
    lines.push(`    return payload as ${responseType};`);
  }

  lines.push("  }");
  return lines;
}

function generateDartIndex() {
  return `${[
    ...dartHeader(),
    "",
    "export 'client.dart';",
    "export 'models.dart';"
  ].join("\n").trimEnd()}\n`;
}

function dartHeader() {
  return generatedHeader.map((line) => `// ${line}`);
}

function dartDescription(description, indent = "") {
  if (!description) {
    return [];
  }

  return [`${indent}/// ${sanitizeComment(description)}`];
}

function dartType(schema, options) {
  const nullableSuffix = options.nullable ? "?" : "";

  if (!schema) {
    return `Object${nullableSuffix}`;
  }

  if (schema.$ref) {
    return `${refName(schema.$ref)}${nullableSuffix}`;
  }

  if (schema.oneOf) {
    const nonNullSchemas = schema.oneOf.filter((child) => child.type !== "null");
    if (nonNullSchemas.length === 1 && schema.oneOf.length !== nonNullSchemas.length) {
      return dartType(nonNullSchemas[0], { nullable: true });
    }

    return `Object${nullableSuffix}`;
  }

  if (schema.type === "null") {
    return "Object?";
  }

  if (schema.type === "string" && schema.format === "date-time") {
    return `DateTime${nullableSuffix}`;
  }

  if (schema.type === "string") {
    return `String${nullableSuffix}`;
  }

  if (schema.type === "integer") {
    return `int${nullableSuffix}`;
  }

  if (schema.type === "number") {
    return `double${nullableSuffix}`;
  }

  if (schema.type === "boolean") {
    return `bool${nullableSuffix}`;
  }

  if (schema.type === "array") {
    return `List<${dartType(schema.items, { nullable: false })}>${nullableSuffix}`;
  }

  if (schema.type === "object" || schema.properties) {
    return `JsonObject${nullableSuffix}`;
  }

  return `Object${nullableSuffix}`;
}

function dartFromJsonExpression(schema, expression, nullable) {
  if (nullable) {
    return `${expression} == null ? null : ${dartFromJsonExpression(schema, expression, false)}`;
  }

  if (schema.$ref) {
    const name = refName(schema.$ref);
    const targetSchema = schemas[name];
    if (schemaIsObject(targetSchema)) {
      return `${name}.fromJson(JsonObject.from(${expression} as Map))`;
    }

    return dartFromJsonExpression(targetSchema, expression, false);
  }

  if (schema.oneOf) {
    const nonNullSchemas = schema.oneOf.filter((child) => child.type !== "null");
    if (nonNullSchemas.length === 1 && schema.oneOf.length !== nonNullSchemas.length) {
      return dartFromJsonExpression(nonNullSchemas[0], expression, true);
    }

    return expression;
  }

  if (schema.type === "string" && schema.format === "date-time") {
    return `DateTime.parse(${expression} as String)`;
  }

  if (schema.type === "string") {
    return `${expression} as String`;
  }

  if (schema.type === "integer") {
    return `(${expression} as num).toInt()`;
  }

  if (schema.type === "number") {
    return `(${expression} as num).toDouble()`;
  }

  if (schema.type === "boolean") {
    return `${expression} as bool`;
  }

  if (schema.type === "array") {
    const itemExpression = dartFromJsonExpression(schema.items, "item", false);
    return `(${expression} as List<dynamic>).map((item) => ${itemExpression}).toList(growable: false)`;
  }

  if (schema.type === "object" || schema.properties) {
    return `JsonObject.from(${expression} as Map)`;
  }

  return expression;
}

function dartToJsonExpression(schema, expression) {
  if (schema.$ref) {
    const targetSchema = schemas[refName(schema.$ref)];
    return schemaIsObject(targetSchema) ? `${expression}.toJson()` : expression;
  }

  if (schema.oneOf) {
    const nonNullSchemas = schema.oneOf.filter((child) => child.type !== "null");
    if (nonNullSchemas.length === 1 && schema.oneOf.length !== nonNullSchemas.length) {
      const inner = dartToJsonExpression(nonNullSchemas[0], expression);
      return inner === expression ? expression : `${expression} == null ? null : ${inner}`;
    }

    return expression;
  }

  if (schema.type === "string" && schema.format === "date-time") {
    return `${expression}.toUtc().toIso8601String()`;
  }

  if (schema.type === "array") {
    const itemExpression = dartToJsonExpression(schema.items, "item");
    return itemExpression === "item" ? expression : `${expression}.map((item) => ${itemExpression}).toList(growable: false)`;
  }

  return expression;
}

function dartPathExpression(path, pathParameters) {
  if (pathParameters.length === 0) {
    return JSON.stringify(path);
  }

  let expression = path;
  for (const parameter of pathParameters) {
    expression = expression.replace(`{${parameter.name}}`, `\${Uri.encodeComponent(${toCamelCase(parameter.name)}.toString())}`);
  }

  return `'${expression}'`;
}

function refName(ref) {
  return ref.split("/").at(-1);
}

function schemaIsObject(schema) {
  return Boolean(schema && (schema.type === "object" || schema.properties));
}

function toPascalCase(value) {
  return value
    .replace(/[^A-Za-z0-9]+/g, " ")
    .split(/(?=[A-Z])|\s+/)
    .filter(Boolean)
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join("");
}

function toCamelCase(value) {
  const pascal = toPascalCase(value);
  if (pascal.length === 0) {
    return value;
  }

  return `${pascal[0].toLowerCase()}${pascal.slice(1)}`;
}

function sanitizeComment(value) {
  return String(value).replace(/\*\//g, "* /").replace(/\s+/g, " ").trim();
}
